# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://demo.robustperception.io:9090
  isDefault: true
  version: 1
  editable: false
